shellEmulator: true

trustPolicy: no-downgrade

packages: []
catalogs:
  cli:
    '@antfu/ni': ^28.1.0
    '@antfu/nip': ^0.1.1
    bumpp: ^10.4.0
    case-police: ^2.1.1
    sponsorkit: ^17.0.0
    taze: ^19.9.2
    vscode-ext-gen: ^1.5.1
  eslint:
    '@antfu/eslint-config': ^7.0.0
    '@stylistic/eslint-plugin': ^5.7.0
    eslint-flat-config-utils: ^2.1.4
    eslint-merge-processors: ^2.0.0
    eslint-plugin-antfu: ^3.1.3
    eslint-plugin-command: ^3.4.0
    eslint-plugin-format: ^1.3.1
    eslint-plugin-pnpm-catalogs: ^0.1.0
    eslint-processor-vue-blocks: ^2.0.0
    eslint-typegen: ^2.3.0
    eslint-vitest-rule-tester: ^3.0.1
  libs:
    '@antfu/install-pkg': ^1.1.0
    '@antfu/utils': ^9.3.0
    birpc: ^4.0.0
    diff-match-patch-es: ^1.0.1
    drauu: ^1.0.0
    fast-npm-meta: ^0.4.7
    importx: ^0.5.2
    local-pkg: ^1.1.2
    magic-string: ^0.30.21
    magic-string-stack: ^1.1.0
    magicast: ^0.5.1
    markdown-it-async: ^2.2.0
    markdown-it-github-alerts: ^1.0.0
    markdown-it-magic-link: ^0.1.4
    node-modules-tools: ^1.2.0
    package-manager-detector: ^1.6.0
    pnpm-catalogs-utils: ^0.1.0
    quansync: ^1.0.0
    strip-literal: ^3.1.0
    structured-clone-es: ^1.0.0
    unconfig: ^7.4.2
    unimport: ^5.6.0
    uqr: ^0.1.2
  nuxt:
    '@nuxt/devtools': ^3.1.1
    '@nuxt/eslint': ^1.12.1
    '@nuxt/icon': ^2.2.0
    nuxt: ^4.2.2
  plugins:
    unplugin: ^2.3.11
    unplugin-auto-import: ^20.3.0
    unplugin-icons: ^23.0.0
    unplugin-vue-components: ^30.0.0
    unplugin-vue-markdown: ^29.2.0
  shiki:
    shiki: ^3.21.0
    shiki-codegen: ^3.21.0
    shiki-magic-move: ^1.2.1
    shiki-stream: ^0.1.4
    shiki-transformer-color-highlight: ^1.0.0
    shiki-transformer-inlay-iconify: ^1.0.0
    twoslash: ^0.3.6
    twoslash-protocol: ^0.3.6
  slidev:
    '@slidev/cli': ^52.11.3
  unocss:
    '@unocss/astro': ^66.5.12
    '@unocss/cli': ^66.5.12
    '@unocss/nuxt': ^66.5.12
    '@unocss/postcss': ^66.5.12
    '@unocss/reset': ^66.5.12
    unocss: ^66.5.12
  unrelated:
    '@types/node': ^25.0.8
    eslint: ^9.39.2
    lint-staged: ^16.2.7
    netlify-plugin-cache: ^1.0.3
    pnpm: ^10.28.0
    simple-git-hooks: ^2.13.1
    typescript: ^5.9.3
  visual:
    '@eslint/config-inspector': ^1.4.2
    '@unocss/inspector': ^66.5.12
    node-modules-inspector: ^1.2.0
    vite-plugin-inspect: ^11.3.3
  vite:
    vite: ^7.3.1
    vite-node: ^5.2.0
    vite-plugin-remote-assets: ^2.1.0
    vite-ssg: ^28.2.2
    vitest: ^4.0.17
  vue:
    '@vueuse/core': ^14.1.0
    '@vueuse/math': ^14.1.0
    vue: ^3.5.26
onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - sharp
  - simple-git-hooks
  - unrs-resolver
  - vue-demi
