packages: []

catalogs:
  cli:
    '@antfu/ni': ^24.3.0
    '@antfu/nip': ^0.0.0
    bumpp: ^10.1.0
    case-police: ^2.0.0
    sponsorkit: ^16.4.2
    taze: ^19.0.4
    vscode-ext-gen: ^1.0.2

  eslint:
    '@antfu/eslint-config': ^4.12.0
    '@stylistic/eslint-plugin': ^4.2.0
    eslint-flat-config-utils: ^2.0.1
    eslint-merge-processors: ^2.0.0
    eslint-plugin-antfu: ^3.1.1
    eslint-plugin-command: ^3.2.0
    eslint-plugin-format: ^1.0.1
    eslint-plugin-pnpm-catalogs: ^0.1.0
    eslint-processor-vue-blocks: ^2.0.0
    eslint-typegen: ^2.1.0
    eslint-vitest-rule-tester: ^2.2.0

  libs:
    '@antfu/install-pkg': ^1.0.0
    '@antfu/utils': ^9.2.0
    birpc: ^2.3.0
    diff-match-patch-es: ^1.0.1
    drauu: ^0.4.3
    fast-npm-meta: ^0.4.1
    importx: ^0.5.2
    local-pkg: ^1.1.1
    magic-string: ^0.30.17
    magic-string-stack: ^1.0.0
    magicast: ^0.3.5
    markdown-it-async: ^2.2.0
    markdown-it-github-alerts: ^1.0.0
    markdown-it-magic-link: ^0.1.4
    node-modules-tools: ^0.6.5
    package-manager-detector: ^1.1.0
    pnpm-catalogs-utils: ^0.1.0
    quansync: ^0.2.10
    strip-literal: ^3.0.0
    structured-clone-es: ^1.0.0
    unconfig: ^7.3.1
    unimport: ^5.0.0
    uqr: ^0.1.2

  nuxt:
    '@nuxt/devtools': ^2.3.2
    '@nuxt/eslint': ^1.3.0
    '@nuxt/icon': ^1.12.0
    nuxt: ^3.16.2

  plugins:
    unplugin: ^2.3.0
    unplugin-auto-import: ^19.1.2
    unplugin-icons: ^22.1.0
    unplugin-vue-components: ^28.4.1
    unplugin-vue-markdown: ^28.3.1

  shiki:
    shiki: ^3.2.2
    shiki-codegen: ^3.2.2
    shiki-magic-move: ^1.1.0
    shiki-stream: ^0.1.2
    shiki-transformer-color-highlight: ^1.0.0
    shiki-transformer-inlay-iconify: ^1.0.0
    twoslash: ^0.3.1
    twoslash-protocol: ^0.3.1

  slidev:
    '@slidev/cli': ^51.5.0

  unocss:
    '@unocss/astro': ^66.0.0
    '@unocss/cli': ^66.0.0
    '@unocss/nuxt': ^66.0.0
    '@unocss/postcss': ^66.0.0
    '@unocss/reset': ^66.0.0
    unocss: ^66.0.0

  unrelated:
    '@types/node': ^22.14.0
    eslint: ^9.24.0
    lint-staged: ^15.5.0
    netlify-plugin-cache: ^1.0.3
    pnpm: ^10.8.0
    simple-git-hooks: ^2.12.1
    typescript: ^5.8.3

  visual:
    '@eslint/config-inspector': ^1.0.2
    '@unocss/inspector': ^66.0.0
    node-modules-inspector: ^0.6.5
    vite-plugin-inspect: ^11.0.0

  vite:
    vite: ^6.2.5
    vite-node: ^3.1.1
    vite-plugin-remote-assets: ^2.0.0
    vite-ssg: ^26.1.1
    vitest: ^3.1.1

  vue:
    '@vueuse/core': ^13.1.0
    '@vueuse/math': ^13.1.0
    vue: ^3.5.13

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - sharp
  - simple-git-hooks
  - vue-demi
