packages: []
catalogs:
  cli:
    '@antfu/ni': ^25.0.0
    '@antfu/nip': ^0.1.0
    bumpp: ^10.2.3
    case-police: ^2.0.0
    sponsorkit: ^16.5.0
    taze: ^19.1.0
    vscode-ext-gen: ^1.1.0
  eslint:
    '@antfu/eslint-config': ^5.2.1
    '@stylistic/eslint-plugin': ^5.2.3
    eslint-flat-config-utils: ^2.1.1
    eslint-merge-processors: ^2.0.0
    eslint-plugin-antfu: ^3.1.1
    eslint-plugin-command: ^3.3.1
    eslint-plugin-format: ^1.0.1
    eslint-plugin-pnpm-catalogs: ^0.1.0
    eslint-processor-vue-blocks: ^2.0.0
    eslint-typegen: ^2.3.0
    eslint-vitest-rule-tester: ^2.2.1
  libs:
    '@antfu/install-pkg': ^1.1.0
    '@antfu/utils': ^9.2.0
    birpc: ^2.5.0
    diff-match-patch-es: ^1.0.1
    drauu: ^0.4.3
    fast-npm-meta: ^0.4.6
    importx: ^0.5.2
    local-pkg: ^1.1.1
    magic-string: ^0.30.17
    magic-string-stack: ^1.1.0
    magicast: ^0.3.5
    markdown-it-async: ^2.2.0
    markdown-it-github-alerts: ^1.0.0
    markdown-it-magic-link: ^0.1.4
    node-modules-tools: ^1.1.1
    package-manager-detector: ^1.3.0
    pnpm-catalogs-utils: ^0.1.0
    quansync: ^0.2.11
    strip-literal: ^3.0.0
    structured-clone-es: ^1.0.0
    unconfig: ^7.3.2
    unimport: ^5.2.0
    uqr: ^0.1.2
  nuxt:
    '@nuxt/devtools': ^2.6.2
    '@nuxt/eslint': ^1.8.0
    '@nuxt/icon': ^2.0.0
    nuxt: ^4.0.3
  plugins:
    unplugin: ^2.3.6
    unplugin-auto-import: ^20.0.0
    unplugin-icons: ^22.2.0
    unplugin-vue-components: ^29.0.0
    unplugin-vue-markdown: ^29.1.0
  shiki:
    shiki: ^3.9.2
    shiki-codegen: ^3.9.2
    shiki-magic-move: ^1.1.0
    shiki-stream: ^0.1.2
    shiki-transformer-color-highlight: ^1.0.0
    shiki-transformer-inlay-iconify: ^1.0.0
    twoslash: ^0.3.4
    twoslash-protocol: ^0.3.4
  slidev:
    '@slidev/cli': ^52.1.0
  unocss:
    '@unocss/astro': ^66.4.2
    '@unocss/cli': ^66.4.2
    '@unocss/nuxt': ^66.4.2
    '@unocss/postcss': ^66.4.2
    '@unocss/reset': ^66.4.2
    unocss: ^66.4.2
  unrelated:
    '@types/node': ^24.3.0
    eslint: ^9.33.0
    lint-staged: ^16.1.5
    netlify-plugin-cache: ^1.0.3
    pnpm: ^10.14.0
    simple-git-hooks: ^2.13.1
    typescript: ^5.9.2
  visual:
    '@eslint/config-inspector': ^1.2.0
    '@unocss/inspector': ^66.4.2
    node-modules-inspector: ^1.1.1
    vite-plugin-inspect: ^11.3.2
  vite:
    vite: ^7.1.2
    vite-node: ^3.2.4
    vite-plugin-remote-assets: ^2.0.0
    vite-ssg: ^28.1.0
    vitest: ^3.2.4
  vue:
    '@vueuse/core': ^13.6.0
    '@vueuse/math': ^13.6.0
    vue: ^3.5.18
onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - sharp
  - simple-git-hooks
  - unrs-resolver
  - vue-demi
