packages: []
catalogs:
  cli:
    '@antfu/ni': ^23.3.1
    bumpp: ^10.0.3
    case-police: ^1.0.0
    sponsorkit: ^16.3.0
    taze: ^18.6.0
    vscode-ext-gen: ^1.0.2

  unocss:
    '@unocss/astro': ^66.0.0
    '@unocss/cli': ^66.0.0
    '@unocss/nuxt': ^66.0.0
    '@unocss/postcss': ^66.0.0
    '@unocss/reset': ^66.0.0
    unocss: ^66.0.0

  slidev:
    '@slidev/cli': ^51.3.0

  nuxt:
    '@nuxt/devtools': ^2.2.1
    '@nuxt/eslint': ^1.1.0
    '@nuxt/icon': ^1.10.3
    nuxt: ^3.15.4
  eslint:
    '@antfu/eslint-config': ^4.7.0
    eslint-flat-config-utils: ^2.0.1
    eslint-merge-processors: ^2.0.0
    eslint-plugin-antfu: ^3.1.0
    eslint-plugin-command: ^3.1.0
    eslint-plugin-format: ^1.0.1
    eslint-plugin-pnpm-catalogs: ^0.1.0
    eslint-processor-vue-blocks: ^2.0.0
    eslint-typegen: ^2.0.0
    eslint-vitest-rule-tester: ^1.1.0
    '@stylistic/eslint-plugin': ^4.2.0

  visual:
    '@eslint/config-inspector': ^1.0.2
    vite-plugin-inspect: ^11.0.0
    node-modules-inspector: ^0.3.0

  shiki:
    shiki: ^3.1.0
    shiki-codegen: ^3.1.0
    shiki-magic-move: ^1.0.1
    shiki-stream: ^0.1.1
    shiki-transformer-color-highlight: ^1.0.0
    shiki-transformer-inlay-iconify: ^1.0.0
    twoslash: ^0.3.1
    twoslash-protocol: ^0.3.1

  plugins:
    unplugin: ^2.2.0
    unplugin-auto-import: ^19.1.1
    unplugin-icons: ^22.1.0
    unplugin-vue-components: ^28.4.1
    unplugin-vue-markdown: ^28.3.1

  libs:
    '@antfu/install-pkg': ^1.0.0
    '@antfu/utils': ^9.1.0
    fast-npm-meta: ^0.3.1
    importx: ^0.5.2
    birpc: ^2.2.0
    local-pkg: ^1.1.1
    magic-string: ^0.30.17
    magic-string-stack: ^1.0.0
    magicast: ^0.3.5
    markdown-it-async: ^2.1.0
    markdown-it-github-alerts: ^0.3.1
    markdown-it-magic-link: ^0.1.4
    drauu: ^0.4.3
    diff-match-patch-es: ^1.0.1
    node-modules-tools: ^0.3.0
    package-manager-detector: ^0.2.11
    pnpm-catalogs-utils: ^0.1.0
    quansync: ^0.2.8
    strip-literal: ^3.0.0
    structured-clone-es: ^1.0.0
    unconfig: ^7.3.0
    unimport: ^4.1.2
    uqr: ^0.1.2

  vite:
    vite: ^6.2.1
    vite-ssg: ^25.2.0
    vite-node: ^3.0.8
    vitest: ^3.0.8

  vue:
    '@vueuse/core': ^12.8.2
    '@vueuse/math': ^12.8.2

  unrelated:
    pnpm: ^10.6.1
    eslint: ^9.21.0
    lint-staged: ^15.4.3
    netlify-plugin-cache: ^1.0.3
    typescript: ^5.8.2
    simple-git-hooks: ^2.11.1
    '@types/node': ^22.13.9
