packages: []
catalogs:
  cli:
    '@antfu/ni': ^25.0.0
    '@antfu/nip': ^0.1.0
    bumpp: ^10.2.0
    case-police: ^2.0.0
    sponsorkit: ^16.5.0
    taze: ^19.1.0
    vscode-ext-gen: ^1.0.2
  eslint:
    '@antfu/eslint-config': ^4.16.1
    '@stylistic/eslint-plugin': ^5.0.0
    eslint-flat-config-utils: ^2.1.0
    eslint-merge-processors: ^2.0.0
    eslint-plugin-antfu: ^3.1.1
    eslint-plugin-command: ^3.3.1
    eslint-plugin-format: ^1.0.1
    eslint-plugin-pnpm-catalogs: ^0.1.0
    eslint-processor-vue-blocks: ^2.0.0
    eslint-typegen: ^2.2.0
    eslint-vitest-rule-tester: ^2.2.0
  libs:
    '@antfu/install-pkg': ^1.1.0
    '@antfu/utils': ^9.2.0
    birpc: ^2.4.0
    diff-match-patch-es: ^1.0.1
    drauu: ^0.4.3
    fast-npm-meta: ^0.4.3
    importx: ^0.5.2
    local-pkg: ^1.1.1
    magic-string: ^0.30.17
    magic-string-stack: ^1.0.0
    magicast: ^0.3.5
    markdown-it-async: ^2.2.0
    markdown-it-github-alerts: ^1.0.0
    markdown-it-magic-link: ^0.1.4
    node-modules-tools: ^1.0.0
    package-manager-detector: ^1.3.0
    pnpm-catalogs-utils: ^0.1.0
    quansync: ^0.2.10
    strip-literal: ^3.0.0
    structured-clone-es: ^1.0.0
    unconfig: ^7.3.2
    unimport: ^5.0.1
    uqr: ^0.1.2
  nuxt:
    '@nuxt/devtools': ^2.5.0
    '@nuxt/eslint': ^1.4.1
    '@nuxt/icon': ^1.14.0
    nuxt: ^3.17.5
  plugins:
    unplugin: ^2.3.5
    unplugin-auto-import: ^19.3.0
    unplugin-icons: ^22.1.0
    unplugin-vue-components: ^28.7.0
    unplugin-vue-markdown: ^28.3.1
  shiki:
    shiki: ^3.7.0
    shiki-codegen: ^3.7.0
    shiki-magic-move: ^1.1.0
    shiki-stream: ^0.1.2
    shiki-transformer-color-highlight: ^1.0.0
    shiki-transformer-inlay-iconify: ^1.0.0
    twoslash: ^0.3.1
    twoslash-protocol: ^0.3.1
  slidev:
    '@slidev/cli': ^51.8.2
  unocss:
    '@unocss/astro': ^66.2.3
    '@unocss/cli': ^66.2.3
    '@unocss/nuxt': ^66.2.3
    '@unocss/postcss': ^66.2.3
    '@unocss/reset': ^66.2.3
    unocss: ^66.2.3
  unrelated:
    '@types/node': ^24.0.3
    eslint: ^9.29.0
    lint-staged: ^16.1.2
    netlify-plugin-cache: ^1.0.3
    pnpm: ^10.12.2
    simple-git-hooks: ^2.13.0
    typescript: ^5.8.3
  visual:
    '@eslint/config-inspector': ^1.1.0
    '@unocss/inspector': ^66.2.3
    node-modules-inspector: ^1.0.0
    vite-plugin-inspect: ^11.2.0
  vite:
    vite: ^6.3.5
    vite-node: ^3.2.4
    vite-plugin-remote-assets: ^2.0.0
    vite-ssg: ^27.0.1
    vitest: ^3.2.4
  vue:
    '@vueuse/core': ^13.4.0
    '@vueuse/math': ^13.4.0
    vue: ^3.5.17
onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - sharp
  - simple-git-hooks
  - unrs-resolver
  - vue-demi
